// Sisyphus
let sisyphusBeginnerGrammar = {
  'verb': ['push','shove','roll'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let sisyphusIntermediateGrammar = {
  'kill': ['kill','murder'],
  'people': ['travellers','guests','visitors'],
  'rule': ['rule','law','principle'],
  'xenia': ['xenia','hospitality','generosity','courtesy'],
  'anger': ['anger','provoke','cheat','reveal the secrets of'],
  'plot': ['plot','scheme'],
  'against': ['against','to #kill#','to dethrone'],
  'Salmoneus': ['Salmoneus','my brother'],
  'Tyro': ['Tyro','my niece','#Salmoneus#\'s daughter'],
  'crime': [
    'seduce #Tyro#',
    '#kill# #people#',
    'break the #rule# of #xenia#',
    '#anger# Zeus',
    'escape from Tartarus',
    '#plot# #against# #Salmoneus#',
    'reveal the location of Aegina',
    'trap Thanatos in chains',
  ],
  'origin': ['I will not #crime#.'],
};
let sisyphusAdvancedStrings = [
  'A hill is a landform that extends above the surrounding terrain. ',
  'It often has a distinct summit, although in areas with scarp/dip topography a hill may refer to a particular section of flat terrain without a massive summit (e.g., Box Hill, Surrey). ',
  'The distinction between a hill and a mountain is unclear and largely subjective, but a hill is universally considered to be less tall and less steep than a mountain. ',
  'In the United Kingdom, geographers historically regarded mountains as hills greater than 1,000 feet (304.8 meters) above sea level, which formed the basis of the plot of the 1995 film The Englishman Who Went Up a Hill But Came Down a Mountain. ',
  'In contrast, hillwalkers have tended to regard mountains as peaks 2,000 feet (610 m) above sea level: ',
  'the Oxford English Dictionary also suggests a limit of 2,000 feet (610 m) and Whittow states "Some authorities regard eminences above 600 m (1,969 ft) as mountains, those below being referred to as hills." ',
  'Today, a mountain is usually defined in the UK and Ireland as any summit at least 2,000 feet or 610 meters high, while the official UK government\'s definition of a mountain is a summit of 600 meters (1,969 feet) or higher. ',
  'Some definitions include a topographical prominence requirement, typically 100 feet (30.5 m) or 500 feet (152.4 m). ',
  'In practice, mountains in Scotland are frequently referred to as "hills" no matter what their height, as reflected in names such as the Cuillin Hills and the Torridon Hills. ',
  'In Wales, the distinction is more a term of land use and appearance and has nothing to do with height. ',
  'For a while, the U.S. ',
  'defined a mountain as being 1,000 feet (304.8 m) or more tall. ',
  'Any similar landform lower than this height was considered a hill. ',
  'The United States Geological Survey (USGS), however, has concluded that these terms do not in fact have technical definitions in the U.S. ',
  'The Great Soviet Encyclopedia defined "hill" as an upland with a relative height up to 200 m (660 ft). ',
  'A hillock is a small hill. ',
  'Other words include knoll and (in Scotland, Northern Ireland and northern England) its variant, knowe. ',
  'Artificial hills may be referred to by a variety of technical names, including mound and tumulus. ',
  'Hills may form through geomorphic phenomena: faulting, erosion of larger landforms such as mountains, and movement and deposition of sediment by glaciers (e.g. ',
  'moraines and drumlins or by erosion exposing solid rock which then weathers down into a hill.) ',
  'The rounded peaks of hills results from the diffusive movement of soil and regolith covering the hill, a process known as downhill creep. ',
  'Various names used to describe types of hill, based on appearance and method of formation. ',
  'Many such names originated in one geographical region to describe a type of hill formation peculiar to that region, though the names are often adopted by geologists and used in a wider geographical context. ',
  'These include: ',
  'Brae – Scottish term for a hillside or brow of a hill. ',
  'Drumlin – an elongated whale-shaped hill formed by glacial action. ',
  'Butte – an isolated hill with steep sides and a small flat top, formed by weathering. ',
  'Kuppe – a rounded hill or low mountain, typical of central Europe ',
  'Tor – a rock formation found on a hilltop; also used to refer to the hill, especially in South West England. ',
  'Puy – used especially in the Auvergne, France, to describe a conical volcanic hill. ',
  'Pingo – a mound of earth-covered ice found in the Arctic and Antarctica. ',
  'Historical significance ',
  'Many settlements were originally built on hills, either to avoid floods (particularly if they were near a large body of water), or for defense (since they offer a good view of the surrounding land and require would-be attackers to fight uphill), or to avoid densely forested areas. ',
  'For example, Ancient Rome was built on seven hills, protecting it from invaders. ',
  'Some settlements, particularly in the Middle East, are located on artificial hills consisting of debris (particularly mud bricks) that has accumulated over many generations. ',
  'Such a location is known as a "tell". ',
  'In northern Europe, many ancient monuments are sited in heaps.[clarification needed] Some of these are defensive structures (such as the hill-forts of the Iron Age), but others appear to have hardly any significance. ',
  'In Britain, many churches at the tops of hills are thought to have been built on the sites of earlier pagan holy places. ',
  'The National Cathedral in Washington, DC has followed this tradition and was built on the highest hill in that city. ',
  'Hills provide a major advantage to an army, giving them an elevated firing position and forcing an opposing army to charge uphill to attack them. ',
  'They may also conceal forces behind them, allowing a force to lie in wait on the crest of a hill, using that crest for cover, and firing on unsuspecting attackers as they broach the hilltop. ',
  'As a result, conventional military strategies often demand possession of high ground. ',
  'Hills have been the sites of many noted battles, such as the first recorded military conflict in Scotland known as the battle of Mons Graupius. ',
  'Modern conflicts include the Battle of Bunker Hill (which was actually fought on Breed\'s Hill) in the American War of Independence and Cemetery Hill and Culp\'s Hill in the Battle of Gettysburg, the turning point of the American Civil War. ',
  'The Battle of San Juan Hill in the Spanish–American War won Americans control of Santiago. ',
  'The Battle of Alesia was also fought from a hilltop fort. ',
  'Fighting on Mamayev Kurgan during the Battle of Stalingrad and the Umurbrogol Pocket in the Battle of Peleliu were also examples of bloody fighting for high ground. ',
  'Another recent example is the Kargil War between India and Pakistan. ',
  'The Great Wall of China is also an example of an advantage provider. ',
  'It is built on mountain tops, and was meant to defend against invaders from the north, and among others, Mongolians. ',
  'Hillwalking is a British English term for a form of hiking which involves the ascent of hills. ',
  'The activity is usually distinguished from mountaineering as it does not involve ropes or technically difficult rock climbing, although the terms mountain and hill are often used interchangeably in Britain. ',
  'Hillwalking is popular in hilly areas such as the English Peak District and the Scottish Highlands. ',
  'Many hills are categorized according to relative height or other criteria and feature on lists named after mountaineers, such as Munros (Scotland) and Wainwrights (England). ',
  'Specific activities such as "peak bagging" (or "Munro bagging") involve climbing hills on these lists with the aim of eventually climbing every hill on the list. ',
  'Cheese rolling is an annual event in the West Country of England which involves rolling a wheel of cheese down a hill. ',
  'Contestants stand at the top and chase the wheel of cheese to the bottom. ',
  'The winner, the one who catches the cheese, gets to keep the wheel of cheese as a prize. ',
];

// Prometheus
let prometheusBeginnerGrammar = {
  'verb': ['struggle','writhe','strain'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let prometheusIntermediateGrammar = {
  'champion': ['champion','help','assist','look after','help out'],
  'fire': ['fire','the fire of creative power'],
  'give': ['gift','provide','give','hand'],
  'humans': ['the humans','humans','humanity','mankind'],
  'crime': [
    'steal #fire#',
    'steal #fire# and #give# it to #humans#',
    'steal #fire# from Hephaestus\'s workshop',
    'hide #fire# in a hollow fennel-stalk',
    'hide #fire# in a hollowed pumpkin',
    'hide #fire# in a hollowed reed',
    'facilitate progress and civilization',
    '#champion# #humans#',
    'pity #humans#',
    'trick Zeus into eating bones and fat',
  ],
  'origin': ['I will not #crime#.'],
};
let prometheusAdvancedStrings = [
   `Escapology is the practice of escaping from restraints or other traps. `,
   `Escapologists (also classified as escape artists) escape from handcuffs, straitjackets, cages, coffins, steel boxes, barrels, bags, burning buildings, fish-tanks, and other perils, often in combination. `,
   `The art of escaping from restraints and confined spaces has been a skill employed by performers for a very long time. `,
   `It was not originally displayed as an overt act in itself but was instead used secretly to create illusions such as a disappearance or transmutation. `,
   `In the 1860s, the Davenport Brothers, who were skilled at releasing themselves from rope ties, used the art to convey the impression they were restrained while they created spirit phenomena. `,
   `Other illusionists, including John Nevil Maskelyne, worked out how the Davenports did their act and re-created the tricks to debunk the brothers' claims of psychic power. `,
   `However, the re-creations did not involve overt escape, merely a replication of tricks with the statement that they were accomplished by secret magicians' skills rather than spirits. `,
   `It took another thirty years before the pure skill of escape began to be displayed as an act in itself. `,
   `The figure most responsible for making escapology a recognized entertainment was Harry Houdini, who built his career on demonstrating the ability to escape from a huge variety of restraints and difficult situations. `,
   `Houdini made no secret of the fact that he was an expert on restraints and the skills needed to overcome them but he often concealed the exact details of his escapes to maintain an air of mystery and suspense. `,
   `Although many of his escapes relied on technical skills such as lock-picking and contortion, he also performed tricks such as Metamorphosis and the Chinese Water Torture Cell, which are essentially classic stage illusions reliant on cleverly designed props. `,
   `Houdini's feats helped to define the basic repertoire of escapology, including escapes from handcuffs, padlocks, straitjackets, mail bags, beer barrels, and prison cells. `,
   `The actual term 'escapology' is reputed to have been coined originally by Australian escapologist and illusionist Murray (Norman Murray Walters), a Houdini contemporary. `,
   `A succession of performers have added new ideas and created variations on old stunts, but it is common for even the best contemporary escapologists to be dubbed modern day "Houdinis". `,
   `Because St. Nicholas Owen successfully escaped the Tower of London and arranged the escape of two Jesuit inmates from the prison, the 16th-century Christian martyr is considered by Catholic escapologists as their patron saint. `,
   `Along with St. John Don Bosco, the two are considered the primary patrons of Catholic Gospel Magicians. `,
   `The United Kingdom Escape Artists was formed in 2004 and is currently the only organisation in the United Kingdom devoted to the promotion of UK escape artists and the preservation of escapology within the UK. `,
   `Its members are made up of professional escapologists, restraint collectors, master locksmiths, and historians. `,
   `The UKEA meet once a year for their AGM. `,
   `The International Escapologists Society is an online society with its own monthly newsletter that is dedicated to the art of escape on an international level. `,
   `Escape Masters (The International Association of Escape Artists) was formed in 1985 by renowned escape artist Norman Bigelow and has been run by Thomas Blacke as International President of the organization and Editor/Publisher of the magazine since 2001. `,
   `Hidden is a style of escape performance popularised by the late Harry Houdini that involved much of the performance taking place behind some form of screen or inside a cabinet in order to protect the secrets of the performer. `,
   `This style of escape performance was popular with the majority of escape artists until the end of the 20th Century and is still preferred by many performers today. `,
   `Its disadvantage is that audiences may wrongly believe a concealed assistant to have released the escapologist, whom they may not have seen struggle. `,
   `Full View is a form of escape performance that was popularised by Norman Bigelow Sr. during the 1970s. `,
   `He presented his escapes as pure tests of human skill and endurance and the audience could actually see everything from start to finish. `,
   `His signature escape, "The Doors Of Death," inspired many escape artists to adopt this style of performance in their own shows. `,
   `One performer, Jonathon Bryce, took the full view approach to the Buried Alive escape and with the encouragement of Norman Bigelow Sr., made the world debut of Buried Alive in Full View at the Music is Art Festival in Buffalo, NY with the help of Goo Goo Dolls bassist, Robby Takac. `,
   `Mark Nelson, "The Great Markini" also performed Full View with his Electrified Mummy Lid Torture Board Escape. `,
   `Escape or Die, the form of escape performance originated by Houdini, is the standard for top-of-the-line escapologists. `,
   `There are at least three possible ways for an escapologist's life to be at risk from the possible failure of this escape. `,
   `These are death by drowning, as in the water escapes Houdini pioneered; death by suffocation, as in escapes from airtight enclosures containing no water, such as coffins; and death by falling, as also originated by Houdini, in a straitjacket escape hanging high above the earth as when Houdini hung from cranes and buildings upside down in a strait jacket where falling would mean certain death. `,
   `UK escape artist Alan Alan took this further by hanging from a burning rope hundreds of feet in the air. `,
   `This type of escapology does fail, and its failures have resulted in escape artists getting hurt or losing their lives. `,
   `Others who have done this type of escape include Dorothy Dietrich, Antony Britton, Jonathon Bryce, and Mark Nelson "Markini The Worlds Youngest Professional Escape Artist" highlighted death by electrocution with his "Electrified Mummy Lid Torture Board". `,
   `Escape was required in under 60 seconds or a fatal charge of electricity would be passed through the chains holding him to the board. `,
   `Occult Escapology is a new style of escapology combining escapology with occult magick so that the escape is part of an occult ritual. `,
   `This makes occult escapology a multidisciplinary subject needing skills in both areas. `,
   `This style of escapology ranges on a continuum where at one extreme the occultism is the main focus (and consequently, simpler items may be utilized), whereas at the other end the element of escape predominates; however, aspects of both occultism and escapology are simultaneously present, not exclusively one or the other. `,
   `This style was invented by occultist, author and occult escapologist S Rob. `,
   `At the time of writing three of the books written by S Rob on occult escapology are at the Magic Castle in Hollywood. `,
   `In 2012, Lucas Wilson, an illusionist from Canada managed the fastest ever recorded escape from a straitjacket while suspended; he escaped in 8.4 seconds while hanging upside down from his ankles at a height of 1m. `,
   `The Grim Game, a 1919 film, stars Harry Houdini as a young man who is bound and imprisoned on numerous occasions by a gang who have kidnapped his fiancée. `,
   `Considered by many as Houdini's best film. `,
   `Lost for over 90 years and rediscovered in 2015 by escape artist and magician Dorothy Dietrich. `,
   `Haldane of the Secret Service a 1924 film, Directed by and Starring Harry Houdini, who is repeatedly restrained by villains who murdered his detective-father. `,
   `Filmed at Beaver Kill Falls in Valatie, NY. `,
   `The novel The Amazing Adventures of Kavalier & Clay, written by Michael Chabon and winner of the 2001 Pulitzer Prize, features escapology as an important plot point. `,
   `Ragtime, by E.L. Doctorow, features Harry Houdini as a major character, and uses escapology as a metaphor for the struggles faced by the American immigrant. `,
   `In American superhero comic books, many superheroes like Batman are trained in escapology, which is invaluable when dealing with deathtraps. `,
   `However, superheroes who are escapologists by profession include Mister Miracle, Ms. Liberty and The Escapist. `,
   `(Mister Miracle and The Escapist were both based on escapologist-turned-comic artist Jim Steranko.) Houdini himself appeared as a time/space traveler in the comic book series Daring Escapes featuring Houdini. `,
   `The 1953 biographical film, Houdini, starring Tony Curtis in the title role, depicted many of Houdini's escapology performances. `,
   `Curtis' performance artist character, The Great Leslie, also performs a suspended straight-jacket escape at the start of the film The Great Race. `,
   `In 1971, Christopher George played an escape artist named Cameron Steele in the TV movie/unsold series pilot, Escape. `,
   `Steele was a non-performing escapologist and night-club owner who, like Bill Bixby's Anthony Blake (The Magician), habitually helped people in trouble. `,
   `In 1982, Griffin O'Neal played a junior escapologist named Danny Masters in the film, The Escape Artist. `,
   `In 1983, real-life escape artist Bill Shirk played himself in a film called The Escapist. `,
   `Yorick, the main character of the comic book Y: The Last Man, is an escape artist. `,
   `In the 1991 film, The Linguini Incident, Rosanna Arquette plays an aspiring escape artist. `,
   `The novels Specific Gravity and Ontario Lacus by J. `,
   `Matthew Neal (2007 and 2008) features a scientist who is also a master escape artist. `,
   `Paul Adam's Escape from Shadow Island, first published in 2009, features young escapologist Max Cassidy. `,
   `Two further books in the series, Jaws of Death and Dead Man's Bay, will be released in April 2011[needs update] and 2012 respectively. `,
   `Adam Phillips's essay "Houdini's Box" uses Houdini himself, as well as a young victim of sexual abuse and other examples, to discuss escapology. `,
   `The console video game Exit focuses around the exploits of the self-proclaimed escapologist known as Mr. ESC. `,
   `In the 2013 film, Now You See Me, Isla Fisher plays an escape artist named Henley Reeves. `,
   `In an interview, she says, "I watched all of Houdini’s work and Dorothy Dietrich, who is a female escapologist, who is amazing, you have to watch her." “I got to train with Dorothy Dietrich, the first lady magician to catch a bullet with her teeth. `,
   `Fisher studied the life and work of Dietrich to prepare for the role. `,
   `"Dorothy is a real female escapologist who is working today. `,
   `She was the first woman to capture a bullet between her teeth, which is an amazing feat. `,
   `She's not only good at misdirection, but she also connects emotionally with the audience, so she's better able to involve them in the stunts." `,
];

// Zeno
let zenoBeginnerGrammar = {
  'verb': ['run','jog','sprint'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let zenoIntermediateGrammar = {
  'champion': ['champion','help','assist','look after','help out'],
  'fire': ['fire','the fire of creative power'],
  'give': ['gift','provide','give','hand'],
  'humans': ['the humans','humans','humanity','mankind'],
  'concoct': ['indulge in', 'concoct','invent','come up with','make up'],
  'cute': ['confusing ','contrarian ','provocative ','annoying ','frustrating ','destructive ','stupid ','irritating ',' '],
  'ideas': ['reductio ad absurdums', 'ideas','thought experiments','theories','arguments'],
  'movement': ['space and time','movement','physics','speed and distance','reality'],
  'crime': [
    '#concoct# #cute##ideas# against #movement#',
  ],
  'origin': ['I will not #crime#.'],
};
let zenoAdvancedGrammar = [
  `In mathematics, a geometric series is a series with a constant ratio between successive terms. `,
  `For example, the series 1/2 + 1/4 + 1/8 + 1/16 + ... is is geometric, because each successive term can be obtained by multiplying the previous term by 1/2. `,
  `Geometric series are among the simplest examples of infinite series with finite sums, although not all of them have this property. `,
  `Historically, geometric series played an important role in the early development of calculus, and they continue to be central in the study of convergence of series. `,
  `Geometric series are used throughout mathematics, and they have important applications in physics, engineering, biology, economics, computer science, queueing theory, and finance. `,
  `The terms of a geometric series form a geometric progression, meaning that the ratio of successive terms in the series is constant. `,
  `This relationship allows for the representation of a geometric series using only two terms, r and a. `,
  `The term r is the common ratio, and a is the first term of the series. `,
  `As an example the geometric series given in the introduction, 1/2 + 1/4 + 1/8 + 1/16 + ... may simply  be written as a + ar + ar^2 + ar^3 + ..., with a = 1/2 and r = 1/2. `,
  `The behavior of the terms depends on the common ratio r: If r is between −1 and +1, the terms of the series approach zero in the limit (becoming smaller and smaller in magnitude), and the series converges to a sum. `,
  `In the case above, where r is 1/2, the series converges to 1. `,
  `If r is greater than one or less than minus one the terms of the series become larger and larger in magnitude. `,
  `The sum of the terms also gets larger and larger, and the series has no sum. (The series diverges.) `,
  `If r is equal to one, all of the terms of the series are the same. The series diverges. `,
  `If r is minus one the terms take two values alternately (e.g. 2, −2, 2, −2, 2,... ). `,
  `The sum of the terms oscillates between two values (e.g. 2, 0, 2, 0, 2,... ). `,
  `This is a different type of divergence and again the series has no sum. See for example Grandi's series: 1 − 1 + 1 − 1 + ···. `,
  `The sum of a geometric series is finite as long as the absolute value of the ratio is less than 1; as the numbers near zero, they become insignificantly small, allowing a sum to be calculated despite the series containing infinitely many terms. `,
  `The sum can be computed using the self-similarity of the series. Consider the sum of the following geometric series: s = 1 + 2/3 + 4/9 + 8/27 + .... `,
  `This series has common ratio 2/3. If we multiply through by this common ratio, then the initial 1 becomes a 2/3, the 2/3 becomes a 4/9, and so on: (2/3)s = 2/3 + 4/9 + 8/27 + 16/81 + .... `,
  `This new series is the same as the original, except that the first term is missing. `,
  `Subtracting the new series (2/3)s from the original series s cancels every term in the original but the first, `,
  `s - 2/3s = 1, so s = 3. A similar technique can be used to evaluate any self-similar expression. `,
  `For r =/= 1, the sum of the first n terms of a geometric series is a + ar + ar^2 + ar^3 + ... + ar^(n-1) = SUM(ar^k) from k=0 to k=n-1 = a((1 - r^n)/(1 - r)), where a is the first term of the series, and r is the common ratio. `,
  `We can derive this formula as follows: s = a + ar + ar^2 + ar^3 + ... + ar^(n-1), rs = ar + ar^2 + ar^3 + ar^4 + ... + ar^n, s - rs = a - ar^n, s(1 - r) = a(1 - r^n), so, s = a((1 - r^n)/(1 - r)) (if r =/= 1). `,
  `As n goes to infinity, the absolute value of r must be less than one for the series to converge. `,
  `The sum then becomes a + ar + ar^2 + ar^3 + ar^4 + ... = SUM(ar^k) from k=0 to k=infinity = a/(1 - r), for |r| < 1. `,
  `When a = 1, this can be simplified to 1 + r + r^2 + r^3 + ... = 1/(1 - r), the left-hand side being a geometric series with common ratio r. `,
  `The formula also holds for complex r, with the corresponding restriction, the modulus of r is strictly less than one. `,
  `We can prove that the geometric series converges using the sum formula for a geometric progression: 1 + r + r^2 + r^3 + ... = lim n->infinity 1 + r + r^2 + ... + r^n = lim n->infinity (1 - r^(n + 1))/(1 - r). `,
  `Since (1 + r + r^2 + ... + r^n)(1 − r) = 1 − r^(n+1) and r^(n+1) -> 0 for |r| < 1. `,
  `Convergence of geometric series can also be demonstrated by rewriting the series as an equivalent telescoping series. `,
  `Consider the function, g(K) = (r^K)/(1 - r). Note that 1 = g(0) - g(1), r = g(1) - g(2), r^2 = g(2) - g(3), ... Thus, S = 1 + r + r^2 + r^3 + ... = (g(0) - g(1)) + (g(1) - g(2)) + (g(2) - g(3)) + .... `,
  `If |r| < 1 then g(K) -> 0 as K -> infinity. So S converges to g(0) = 1/(1 - r). `,
  `A repeating decimal can be thought of as a geometric series whose common ratio is a power of 1/10. For example: 0.7777... = 7/10 + 7/100 + 7/1000 + 7/10000 + .... `,
  `The formula for the sum of a geometric series can be used to convert the decimal to a fraction, 0.7777... = a/(1 - r) = (7/10)/(1 - 1/10) = (7/10)/(9/10) = 7/9. `,
  `The formula works not only for a single repeating figure, but also for a repeating group of figures. For example: 0.123412341234... = a/(1 - r) = (1234/10000)/(1 - 1/10000) = (1234/10000)/(9999/10000) = 1234/9999. `,
  `Note that every series of repeating consecutive decimals can be conveniently simplified with the following: 0.09090909... = 09/99 = 1/11. 0.143814381438... = 1439/9999. 0.9999... = 9/9 = 1. `,
  `That is, a repeating decimal with repeat length n is equal to the quotient of the repeating part (as an integer) and 10^n - 1. `,
  `In the study of fractals, geometric series often arise as the perimeter, area, or volume of a self-similar figure. For example, the area inside the Koch snowflake can be described as the union of infinitely many equilateral triangles. `,
  `Each side of the second-level triangle is exactly 1/3 the size of a side of the largest triangle, and therefore has exactly 1/9 the area. Similarly, each third-level triangle has 1/9 the area of a second-level triangle, and so forth. Taking the largest triangle as a unit of area, the total area of the snowflake is 1 + 3(1/9) + 12(1/9)^2 + 48(1/9)^3 + .... `,
  `The first term of this series represents the area of the largest triangle, the second term the total area of the three second-level triangles, the third term the total area of the twelve third-level triangles, and so forth. `,
  `Excluding the initial 1, this series is geometric with constant ratio r = 4/9. The first term of the geometric series is a = 3(1/9) = 1/3, so the sum is 1 + a/(1 - r) = 1 + (1/3)/(1 - 4/9) = 8/5. Thus the Koch snowflake has 8/5 of the area of the base triangle. `,
  `The convergence of a geometric series reveals that a sum involving an infinite number of summands can indeed be finite, and so allows one to resolve many of Zeno's paradoxes. `,
  `For example, Zeno's dichotomy paradox maintains that movement is impossible, as one can divide any finite path into an infinite number of steps wherein each step is taken to be half the remaining distance. `,
  `Zeno's mistake is in the assumption that the sum of an infinite number of finite steps cannot be finite. This is of course not true, as evidenced by the convergence of the geometric series with r = 1/2. `,
  `Book IX, Proposition 35 of Euclid's Elements expresses the partial sum of a geometric series in terms of members of the series. It is equivalent to the modern formula. `,
  `In economics, geometric series are used to represent the present value of an annuity (a sum of money to be paid in regular intervals). `,
  `For example, suppose that a payment of $100 will be made to the owner of the annuity once per year (at the end of the year) in perpetuity. Receiving $100 a year from now is worth less than an immediate $100, because one cannot invest the money until one receives it. In particular, the present value of $100 one year in the future is $100 / (1 + I ), where I is the yearly interest rate. `,
  `Similarly, a payment of $100 two years in the future has a present value of $100 / (1 + I)^2 (squared because two years' worth of interest is lost by not receiving the money right now). Therefore, the present value of receiving $100 per year in perpetuity is SUM($100/(1 + I)^n) for n = 1 to n = infinity which is the infinite series: $100/(1 + I) + $100/(1 + I)^2 + $100/(1 + I)^3 + $100/(1 + I)^4 + .... `,
  `This is a geometric series with common ratio 1 / (1 + I). The sum is the first term divided by (one minus the common ratio): ($100/(1 + I))/(1 - 1/(1 + I)) = $100/I. `,
  `For example, if the yearly interest rate is 10% (I = 0.10), then the entire annuity has a present value of $100 / 0.10 = $1000. `,
  `This sort of calculation is used to compute the APR of a loan (such as a mortgage loan). It can also be used to estimate the present value of expected stock dividends, or the terminal value of a security. `,
];

// Camus
let camusStrings = [
  'The gods had condemned Sisyphus to ceaselessly rolling a rock to the top of a mountain, whence the stone would fall back of its own weight. ',
  'They had thought with some reason that there is no more dreadful punishment than futile and hopeless labor. ',
  'If one believes Homer, Sisyphus was the wisest and most prudent of mortals. ',
  'According to another tradition, however, he was disposed to practice the profession of highwayman. ',
  'I see no contradiction in this. ',
  'Opinions differ as to the reasons why he became the futile laborer of the underworld. ',
  'To begin with, he is accused of a certain levity in regard to the gods. ',
  'He stole their secrets. ',
  'Egina, the daughter of Esopus, was carried off by Jupiter. ',
  'The father was shocked by that disappearance and complained to Sisyphus. ',
  'He, who knew of the abduction, offered to tell about it on condition that Esopus would give water to the citadel of Corinth. ',
  'To the celestial thunderbolts he preferred the benediction of water. ',
  'He was punished for this in the underworld. ',
  'Homer tells us also that Sisyphus had put Death in chains. ',
  'Pluto could not endure the sight of his deserted, silent empire. ',
  'He dispatched the god of war, who liberated Death from the hands of her conqueror. ',
  'It is said that Sisyphus, being near to death, rashly wanted to test his wife\'s love. ',
  'He ordered her to cast his unburied body into the middle of the public square. ',
  'Sisyphus woke up in the underworld. ',
  'And there, annoyed by an obedience so contrary to human love, he obtained from Pluto permission to return to earth in order to chastise his wife. ',
  'But when he had seen again the face of this world, enjoyed water and sun, warm stones and the sea, he no longer wanted to go back to the infernal darkness. ',
  'Recalls, signs of anger, warnings were of no avail. ',
  'Many years more he lived facing the curve of the gulf, the sparkling sea, and the smiles of earth. ',
  'A decree of the gods was necessary. ',
  'Mercury came and seized the impudent man by the collar and, snatching him from his joys, lead him forcibly back to the underworld, where his rock was ready for him. ',
  'You have already grasped that Sisyphus is the absurd hero. ',
  'He is, as much through his passions as through his torture. ',
  'His scorn of the gods, his hatred of death, and his passion for life won him that unspeakable penalty in which the whole being is exerted toward accomplishing nothing. ',
  'This is the price that must be paid for the passions of this earth. ',
  'Nothing is told us about Sisyphus in the underworld. ',
  'Myths are made for the imagination to breathe life into them. ',
  'As for this myth, one sees merely the whole effort of a body straining to raise the huge stone, to roll it, and push it up a slope a hundred times over; one sees the face screwed up, the cheek tight against the stone, the shoulder bracing the clay-covered mass, the foot wedging it, the fresh start with arms outstretched, the wholly human security of two earth-clotted hands. ',
  'At the very end of his long effort measured by skyless space and time without depth, the purpose is achieved. ',
  'Then Sisyphus watches the stone rush down in a few moments toward that lower world whence he will have to push it up again toward the summit. ',
  'He goes back down to the plain. ',
  'It is during that return, that pause, that Sisyphus interests me. ',
  'A face that toils so close to stones is already stone itself! I see that man going back down with a heavy yet measured step toward the torment of which he will never know the end. ',
  'That hour like a breathing-space which returns as surely as his suffering, that is the hour of consciousness. ',
  'At each of those moments when he leaves the heights and gradually sinks toward the lairs of the gods, he is superior to his fate. ',
  'He is stronger than his rock. ',
  'If this myth is tragic, that is because its hero is conscious. ',
  'Where would his torture be, indeed, if at every step the hope of succeeding upheld him? The workman of today works everyday in his life at the same tasks, and his fate is no less absurd. ',
  'But it is tragic only at the rare moments when it becomes conscious. ',
  'Sisyphus, proletarian of the gods, powerless and rebellious, knows the whole extent of his wretched condition: it is what he thinks of during his descent. ',
  'The lucidity that was to constitute his torture at the same time crowns his victory. ',
  'There is no fate that can not be surmounted by scorn. ',
  'If the descent is thus sometimes performed in sorrow, it can also take place in joy. ',
  'This word is not too much. ',
  'Again I fancy Sisyphus returning toward his rock, and the sorrow was in the beginning. ',
  'When the images of earth cling too tightly to memory, when the call of happiness becomes too insistent, it happens that melancholy arises in man\'s heart: this is the rock\'s victory, this is the rock itself. ',
  'The boundless grief is too heavy to bear. ',
  'These are our nights of Gethsemane. ',
  'But crushing truths perish from being acknowledged. ',
  'Thus, Edipus at the outset obeys fate without knowing it. ',
  'But from the moment he knows, his tragedy begins. ',
  'Yet at the same moment, blind and desperate, he realizes that the only bond linking him to the world is the cool hand of a girl. ',
  'Then a tremendous remark rings out: "Despite so many ordeals, my advanced age and the nobility of my soul make me conclude that all is well." Sophocles\' Edipus, like Dostoevsky\'s Kirilov, thus gives the recipe for the absurd victory. ',
  'Ancient wisdom confirms modern heroism. ',
  'One does not discover the absurd without being tempted to write a manual of happiness. ',
  '"What!---by such narrow ways--?" There is but one world, however. ',
  'Happiness and the absurd are two sons of the same earth. ',
  'They are inseparable. ',
  'It would be a mistake to say that happiness necessarily springs from the absurd. ',
  'discovery. ',
  'It happens as well that the felling of the absurd springs from happiness. ',
  '"I conclude that all is well," says Edipus, and that remark is sacred. ',
  'It echoes in the wild and limited universe of man. ',
  'It teaches that all is not, has not been, exhausted. ',
  'It drives out of this world a god who had come into it with dissatisfaction and a preference for futile suffering. ',
  'It makes of fate a human matter, which must be settled among men. ',
  'All Sisyphus\' silent joy is contained therein. ',
  'His fate belongs to him. ',
  'His rock is a thing Likewise, the absurd man, when he contemplates his torment, silences all the idols. ',
  'In the universe suddenly restored to its silence, the myriad wondering little voices of the earth rise up. ',
  'Unconscious, secret calls, invitations from all the faces, they are the necessary reverse and price of victory. ',
  'There is no sun without shadow, and it is essential to know the night. ',
  'The absurd man says yes and his efforts will henceforth be unceasing. ',
  'If there is a personal fate, there is no higher destiny, or at least there is, but one which he concludes is inevitable and despicable. ',
  'For the rest, he knows himself to be the master of his days. ',
  'At that subtle moment when man glances backward over his life, Sisyphus returning toward his rock, in that slight pivoting he contemplates that series of unrelated actions which become his fate, created by him, combined under his memory\'s eye and soon sealed by his death. ',
  'Thus, convinced of the wholly human origin of all that is human, a blind man eager to see who knows that the night has no end, he is still on the go. ',
  'The rock is still rolling. ',
  'I leave Sisyphus at the foot of the mountain! One always finds one\'s burden again. ',
  'But Sisyphus teaches the higher fidelity that negates the gods and raises rocks. ',
  'He too concludes that all is well. ',
  'This universe henceforth without a master seems to him neither sterile nor futile. ',
  'Each atom of that stone, each mineral flake of that night filled mountain, in itself forms a world. ',
  'The verb itself toward the heights is enough to fill a man\'s heart. ',
  'One must imagine Sisyphus happy. '
];
