// Sisyphus
let sisyphusBeginnerGrammar = {
  'verb': ['push','shove','roll'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let sisyphusIntermediateGrammar = {
  'kill': ['kill','murder'],
  'people': ['travellers','guests','visitors'],
  'rule': ['rule','law','principle'],
  'xenia': ['xenia','hospitality','generosity','courtesy'],
  'anger': ['anger','provoke','cheat','reveal the secrets of'],
  'plot': ['plot','scheme'],
  'against': ['against','to #kill#','to dethrone'],
  'Salmoneus': ['Salmoneus','my brother'],
  'Tyro': ['Tyro','my niece','#Salmoneus#\'s daughter'],
  'crime': [
    'seduce #Tyro#',
    '#kill# #people#',
    'break the #rule# of #xenia#',
    '#anger# Zeus',
    'escape from Tartarus',
    '#plot# #against# #Salmoneus#',
    'reveal the location of Aegina',
    'trap Thanatos in chains',
  ],
  'origin': ['I will not #crime#.'],
};
let sisyphusAdvancedStrings = [
  'A hill is a landform that extends above the surrounding terrain. ',
  'It often has a distinct summit, although in areas with scarp/dip topography a hill may refer to a particular section of flat terrain without a massive summit (e.g., Box Hill, Surrey). ',
  'The distinction between a hill and a mountain is unclear and largely subjective, but a hill is universally considered to be less tall and less steep than a mountain. ',
  'In the United Kingdom, geographers historically regarded mountains as hills greater than 1,000 feet (304.8 meters) above sea level, which formed the basis of the plot of the 1995 film The Englishman Who Went Up a Hill But Came Down a Mountain. ',
  'In contrast, hillwalkers have tended to regard mountains as peaks 2,000 feet (610 m) above sea level: ',
  'the Oxford English Dictionary also suggests a limit of 2,000 feet (610 m) and Whittow states "Some authorities regard eminences above 600 m (1,969 ft) as mountains, those below being referred to as hills." ',
  'Today, a mountain is usually defined in the UK and Ireland as any summit at least 2,000 feet or 610 meters high, while the official UK government\'s definition of a mountain is a summit of 600 meters (1,969 feet) or higher. ',
  'Some definitions include a topographical prominence requirement, typically 100 feet (30.5 m) or 500 feet (152.4 m). ',
  'In practice, mountains in Scotland are frequently referred to as "hills" no matter what their height, as reflected in names such as the Cuillin Hills and the Torridon Hills. ',
  'In Wales, the distinction is more a term of land use and appearance and has nothing to do with height. ',
  'For a while, the U.S. ',
  'defined a mountain as being 1,000 feet (304.8 m) or more tall. ',
  'Any similar landform lower than this height was considered a hill. ',
  'The United States Geological Survey (USGS), however, has concluded that these terms do not in fact have technical definitions in the U.S. ',
  'The Great Soviet Encyclopedia defined "hill" as an upland with a relative height up to 200 m (660 ft). ',
  'A hillock is a small hill. ',
  'Other words include knoll and (in Scotland, Northern Ireland and northern England) its variant, knowe. ',
  'Artificial hills may be referred to by a variety of technical names, including mound and tumulus. ',
  'Hills may form through geomorphic phenomena: faulting, erosion of larger landforms such as mountains, and movement and deposition of sediment by glaciers (e.g. ',
  'moraines and drumlins or by erosion exposing solid rock which then weathers down into a hill.) ',
  'The rounded peaks of hills results from the diffusive movement of soil and regolith covering the hill, a process known as downhill creep. ',
  'Various names used to describe types of hill, based on appearance and method of formation. ',
  'Many such names originated in one geographical region to describe a type of hill formation peculiar to that region, though the names are often adopted by geologists and used in a wider geographical context. ',
  'These include: ',
  'Brae – Scottish term for a hillside or brow of a hill. ',
  'Drumlin – an elongated whale-shaped hill formed by glacial action. ',
  'Butte – an isolated hill with steep sides and a small flat top, formed by weathering. ',
  'Kuppe – a rounded hill or low mountain, typical of central Europe ',
  'Tor – a rock formation found on a hilltop; also used to refer to the hill, especially in South West England. ',
  'Puy – used especially in the Auvergne, France, to describe a conical volcanic hill. ',
  'Pingo – a mound of earth-covered ice found in the Arctic and Antarctica. ',
  'Historical significance ',
  'Many settlements were originally built on hills, either to avoid floods (particularly if they were near a large body of water), or for defense (since they offer a good view of the surrounding land and require would-be attackers to fight uphill), or to avoid densely forested areas. ',
  'For example, Ancient Rome was built on seven hills, protecting it from invaders. ',
  'Some settlements, particularly in the Middle East, are located on artificial hills consisting of debris (particularly mud bricks) that has accumulated over many generations. ',
  'Such a location is known as a "tell". ',
  'In northern Europe, many ancient monuments are sited in heaps.[clarification needed] Some of these are defensive structures (such as the hill-forts of the Iron Age), but others appear to have hardly any significance. ',
  'In Britain, many churches at the tops of hills are thought to have been built on the sites of earlier pagan holy places. ',
  'The National Cathedral in Washington, DC has followed this tradition and was built on the highest hill in that city. ',
  'Hills provide a major advantage to an army, giving them an elevated firing position and forcing an opposing army to charge uphill to attack them. ',
  'They may also conceal forces behind them, allowing a force to lie in wait on the crest of a hill, using that crest for cover, and firing on unsuspecting attackers as they broach the hilltop. ',
  'As a result, conventional military strategies often demand possession of high ground. ',
  'Hills have been the sites of many noted battles, such as the first recorded military conflict in Scotland known as the battle of Mons Graupius. ',
  'Modern conflicts include the Battle of Bunker Hill (which was actually fought on Breed\'s Hill) in the American War of Independence and Cemetery Hill and Culp\'s Hill in the Battle of Gettysburg, the turning point of the American Civil War. ',
  'The Battle of San Juan Hill in the Spanish–American War won Americans control of Santiago. ',
  'The Battle of Alesia was also fought from a hilltop fort. ',
  'Fighting on Mamayev Kurgan during the Battle of Stalingrad and the Umurbrogol Pocket in the Battle of Peleliu were also examples of bloody fighting for high ground. ',
  'Another recent example is the Kargil War between India and Pakistan. ',
  'The Great Wall of China is also an example of an advantage provider. ',
  'It is built on mountain tops, and was meant to defend against invaders from the north, and among others, Mongolians. ',
  'Hillwalking is a British English term for a form of hiking which involves the ascent of hills. ',
  'The activity is usually distinguished from mountaineering as it does not involve ropes or technically difficult rock climbing, although the terms mountain and hill are often used interchangeably in Britain. ',
  'Hillwalking is popular in hilly areas such as the English Peak District and the Scottish Highlands. ',
  'Many hills are categorized according to relative height or other criteria and feature on lists named after mountaineers, such as Munros (Scotland) and Wainwrights (England). ',
  'Specific activities such as "peak bagging" (or "Munro bagging") involve climbing hills on these lists with the aim of eventually climbing every hill on the list. ',
  'Cheese rolling is an annual event in the West Country of England which involves rolling a wheel of cheese down a hill. ',
  'Contestants stand at the top and chase the wheel of cheese to the bottom. ',
  'The winner, the one who catches the cheese, gets to keep the wheel of cheese as a prize. ',
];

// Prometheus
let prometheusBeginnerGrammar = {
  'verb': ['struggle','writhe','strain'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let prometheusIntermediateGrammar = {
  'champion': ['champion','help','assist','look after','help out'],
  'fire': ['fire','the fire of creative power'],
  'give': ['gift','provide','give','hand'],
  'humans': ['the humans','humans','humanity','mankind'],
  'crime': [
    'steal #fire#',
    'steal #fire# and #give# it to #humans#',
    'steal #fire# from Hephaestus\'s workshop',
    'hide #fire# in a hollow fennel-stalk',
    'hide #fire# in a hollowed pumpkin',
    'hide #fire# in a hollowed reed',
    'facilitate progress and civilization',
    '#champion# #humans#',
    'pity #humans#',
    'trick Zeus into eating bones and fat',
  ],
  'origin': ['I will not #crime#.'],
};
let prometheusAdvancedStrings = [
  `Escapology is the practice of escaping from restraints or other traps. `,
  `Escapologists (also classified as escape artists) escape from handcuffs, straitjackets, cages, coffins, steel boxes, barrels, bags, burning buildings, fish-tanks, and other perils, often in combination. `,
  `The art of escaping from restraints and confined spaces has been a skill employed by performers for a very long time. `,
  `It was not originally displayed as an overt act in itself but was instead used secretly to create illusions such as a disappearance or transmutation. `,
  `In the 1860s, the Davenport Brothers, who were skilled at releasing themselves from rope ties, used the art to convey the impression they were restrained while they created spirit phenomena. `,
  `Other illusionists, including John Nevil Maskelyne, worked out how the Davenports did their act and re-created the tricks to debunk the brothers' claims of psychic power. `,
  `However, the re-creations did not involve overt escape, merely a replication of tricks with the statement that they were accomplished by secret magicians' skills rather than spirits. `,
  `It took another thirty years before the pure skill of escape began to be displayed as an act in itself. `,
  `The figure most responsible for making escapology a recognized entertainment was Harry Houdini, who built his career on demonstrating the ability to escape from a huge variety of restraints and difficult situations. `,
  `Houdini made no secret of the fact that he was an expert on restraints and the skills needed to overcome them but he often concealed the exact details of his escapes to maintain an air of mystery and suspense. `,
  `Although many of his escapes relied on technical skills such as lock-picking and contortion, he also performed tricks such as Metamorphosis and the Chinese Water Torture Cell, which are essentially classic stage illusions reliant on cleverly designed props. `,
  `Houdini's feats helped to define the basic repertoire of escapology, including escapes from handcuffs, padlocks, straitjackets, mail bags, beer barrels, and prison cells. `,
  `The actual term 'escapology' is reputed to have been coined originally by Australian escapologist and illusionist Murray (Norman Murray Walters), a Houdini contemporary. `,
  `A succession of performers have added new ideas and created variations on old stunts, but it is common for even the best contemporary escapologists to be dubbed modern day "Houdinis". `,
  `Because St. Nicholas Owen successfully escaped the Tower of London and arranged the escape of two Jesuit inmates from the prison, the 16th-century Christian martyr is considered by Catholic escapologists as their patron saint. `,
  `Along with St. John Don Bosco, the two are considered the primary patrons of Catholic Gospel Magicians. `,
  `The United Kingdom Escape Artists was formed in 2004 and is currently the only organisation in the United Kingdom devoted to the promotion of UK escape artists and the preservation of escapology within the UK. `,
  `Its members are made up of professional escapologists, restraint collectors, master locksmiths, and historians. `,
  `The UKEA meet once a year for their AGM. `,
  `The International Escapologists Society is an online society with its own monthly newsletter that is dedicated to the art of escape on an international level. `,
  `Escape Masters (The International Association of Escape Artists) was formed in 1985 by renowned escape artist Norman Bigelow and has been run by Thomas Blacke as International President of the organization and Editor/Publisher of the magazine since 2001. `,
  `Hidden is a style of escape performance popularised by the late Harry Houdini that involved much of the performance taking place behind some form of screen or inside a cabinet in order to protect the secrets of the performer. `,
  `This style of escape performance was popular with the majority of escape artists until the end of the 20th Century and is still preferred by many performers today. `,
  `Its disadvantage is that audiences may wrongly believe a concealed assistant to have released the escapologist, whom they may not have seen struggle. `,
  `Full View is a form of escape performance that was popularised by Norman Bigelow Sr. during the 1970s. `,
  `He presented his escapes as pure tests of human skill and endurance and the audience could actually see everything from start to finish. `,
  `His signature escape, "The Doors Of Death," inspired many escape artists to adopt this style of performance in their own shows. `,
  `One performer, Jonathon Bryce, took the full view approach to the Buried Alive escape and with the encouragement of Norman Bigelow Sr., made the world debut of Buried Alive in Full View at the Music is Art Festival in Buffalo, NY with the help of Goo Goo Dolls bassist, Robby Takac. `,
  `Mark Nelson, "The Great Markini" also performed Full View with his Electrified Mummy Lid Torture Board Escape. `,
  `Escape or Die, the form of escape performance originated by Houdini, is the standard for top-of-the-line escapologists. `,
  `There are at least three possible ways for an escapologist's life to be at risk from the possible failure of this escape. `,
  `These are death by drowning, as in the water escapes Houdini pioneered; death by suffocation, as in escapes from airtight enclosures containing no water, such as coffins; and death by falling, as also originated by Houdini, in a straitjacket escape hanging high above the earth as when Houdini hung from cranes and buildings upside down in a strait jacket where falling would mean certain death. `,
  `UK escape artist Alan Alan took this further by hanging from a burning rope hundreds of feet in the air. `,
  `This type of escapology does fail, and its failures have resulted in escape artists getting hurt or losing their lives. `,
  `Others who have done this type of escape include Dorothy Dietrich, Antony Britton, Jonathon Bryce, and Mark Nelson "Markini The Worlds Youngest Professional Escape Artist" highlighted death by electrocution with his "Electrified Mummy Lid Torture Board". `,
  `Escape was required in under 60 seconds or a fatal charge of electricity would be passed through the chains holding him to the board. `,
  `Occult Escapology is a new style of escapology combining escapology with occult magick so that the escape is part of an occult ritual. `,
  `This makes occult escapology a multidisciplinary subject needing skills in both areas. `,
  `This style of escapology ranges on a continuum where at one extreme the occultism is the main focus (and consequently, simpler items may be utilized), whereas at the other end the element of escape predominates; however, aspects of both occultism and escapology are simultaneously present, not exclusively one or the other. `,
  `This style was invented by occultist, author and occult escapologist S Rob. `,
  `At the time of writing three of the books written by S Rob on occult escapology are at the Magic Castle in Hollywood. `,
  `In 2012, Lucas Wilson, an illusionist from Canada managed the fastest ever recorded escape from a straitjacket while suspended; he escaped in 8.4 seconds while hanging upside down from his ankles at a height of 1m. `,
  `The Grim Game, a 1919 film, stars Harry Houdini as a young man who is bound and imprisoned on numerous occasions by a gang who have kidnapped his fiancée. `,
  `Considered by many as Houdini's best film. `,
  `Lost for over 90 years and rediscovered in 2015 by escape artist and magician Dorothy Dietrich. `,
  `Haldane of the Secret Service a 1924 film, Directed by and Starring Harry Houdini, who is repeatedly restrained by villains who murdered his detective-father. `,
  `Filmed at Beaver Kill Falls in Valatie, NY. `,
  `The novel The Amazing Adventures of Kavalier & Clay, written by Michael Chabon and winner of the 2001 Pulitzer Prize, features escapology as an important plot point. `,
  `Ragtime, by E.L. Doctorow, features Harry Houdini as a major character, and uses escapology as a metaphor for the struggles faced by the American immigrant. `,
  `In American superhero comic books, many superheroes like Batman are trained in escapology, which is invaluable when dealing with deathtraps. `,
  `However, superheroes who are escapologists by profession include Mister Miracle, Ms. Liberty and The Escapist. `,
  `(Mister Miracle and The Escapist were both based on escapologist-turned-comic artist Jim Steranko.) Houdini himself appeared as a time/space traveler in the comic book series Daring Escapes featuring Houdini. `,
  `The 1953 biographical film, Houdini, starring Tony Curtis in the title role, depicted many of Houdini's escapology performances. `,
  `Curtis' performance artist character, The Great Leslie, also performs a suspended straight-jacket escape at the start of the film The Great Race. `,
  `In 1971, Christopher George played an escape artist named Cameron Steele in the TV movie/unsold series pilot, Escape. `,
  `Steele was a non-performing escapologist and night-club owner who, like Bill Bixby's Anthony Blake (The Magician), habitually helped people in trouble. `,
  `In 1982, Griffin O'Neal played a junior escapologist named Danny Masters in the film, The Escape Artist. `,
  `In 1983, real-life escape artist Bill Shirk played himself in a film called The Escapist. `,
  `Yorick, the main character of the comic book Y: The Last Man, is an escape artist. `,
  `In the 1991 film, The Linguini Incident, Rosanna Arquette plays an aspiring escape artist. `,
  `The novels Specific Gravity and Ontario Lacus by J. `,
  `Matthew Neal (2007 and 2008) features a scientist who is also a master escape artist. `,
  `Paul Adam's Escape from Shadow Island, first published in 2009, features young escapologist Max Cassidy. `,
  `Two further books in the series, Jaws of Death and Dead Man's Bay, will be released in April 2011[needs update] and 2012 respectively. `,
  `Adam Phillips's essay "Houdini's Box" uses Houdini himself, as well as a young victim of sexual abuse and other examples, to discuss escapology. `,
  `The console video game Exit focuses around the exploits of the self-proclaimed escapologist known as Mr. ESC. `,
  `In the 2013 film, Now You See Me, Isla Fisher plays an escape artist named Henley Reeves. `,
  `In an interview, she says, "I watched all of Houdini’s work and Dorothy Dietrich, who is a female escapologist, who is amazing, you have to watch her." “I got to train with Dorothy Dietrich, the first lady magician to catch a bullet with her teeth. `,
  `Fisher studied the life and work of Dietrich to prepare for the role. `,
  `"Dorothy is a real female escapologist who is working today. `,
  `She was the first woman to capture a bullet between her teeth, which is an amazing feat. `,
  `She's not only good at misdirection, but she also connects emotionally with the audience, so she's better able to involve them in the stunts." `,
];

// Zeno
let zenoBeginnerGrammar = {
  'verb': ['run','jog','sprint'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let zenoIntermediateGrammar = {
  'champion': ['champion','help','assist','look after','help out'],
  'fire': ['fire','the fire of creative power'],
  'give': ['gift','provide','give','hand'],
  'humans': ['the humans','humans','humanity','mankind'],
  'concoct': ['indulge in', 'concoct','invent','come up with','make up'],
  'cute': ['confusing ','contrarian ','provocative ','annoying ','frustrating ','destructive ','stupid ','irritating ',' '],
  'ideas': ['reductio ad absurdums', 'ideas','thought experiments','theories','arguments'],
  'movement': ['space and time','movement','physics','speed and distance','reality'],
  'crime': [
    '#concoct# #cute##ideas# against #movement#',
  ],
  'origin': ['I will not #crime#.'],
};
let zenoAdvancedStrings = [
  `In mathematics, a geometric series is a series with a constant ratio between successive terms. `,
  `For example, the series 1/2 + 1/4 + 1/8 + 1/16 + ... is is geometric, because each successive term can be obtained by multiplying the previous term by 1/2. `,
  `Geometric series are among the simplest examples of infinite series with finite sums, although not all of them have this property. `,
  `Historically, geometric series played an important role in the early development of calculus, and they continue to be central in the study of convergence of series. `,
  `Geometric series are used throughout mathematics, and they have important applications in physics, engineering, biology, economics, computer science, queueing theory, and finance. `,
  `The terms of a geometric series form a geometric progression, meaning that the ratio of successive terms in the series is constant. `,
  `This relationship allows for the representation of a geometric series using only two terms, r and a. `,
  `The term r is the common ratio, and a is the first term of the series. `,
  `As an example the geometric series given in the introduction, 1/2 + 1/4 + 1/8 + 1/16 + ... may simply  be written as a + ar + ar^2 + ar^3 + ..., with a = 1/2 and r = 1/2. `,
  `The behavior of the terms depends on the common ratio r: If r is between −1 and +1, the terms of the series approach zero in the limit (becoming smaller and smaller in magnitude), and the series converges to a sum. `,
  `In the case above, where r is 1/2, the series converges to 1. `,
  `If r is greater than one or less than minus one the terms of the series become larger and larger in magnitude. `,
  `The sum of the terms also gets larger and larger, and the series has no sum. (The series diverges.) `,
  `If r is equal to one, all of the terms of the series are the same. The series diverges. `,
  `If r is minus one the terms take two values alternately (e.g. 2, −2, 2, −2, 2,... ). `,
  `The sum of the terms oscillates between two values (e.g. 2, 0, 2, 0, 2,... ). `,
  `This is a different type of divergence and again the series has no sum. See for example Grandi's series: 1 − 1 + 1 − 1 + ···. `,
  `The sum of a geometric series is finite as long as the absolute value of the ratio is less than 1; as the numbers near zero, they become insignificantly small, allowing a sum to be calculated despite the series containing infinitely many terms. `,
  `The sum can be computed using the self-similarity of the series. Consider the sum of the following geometric series: s = 1 + 2/3 + 4/9 + 8/27 + .... `,
  `This series has common ratio 2/3. If we multiply through by this common ratio, then the initial 1 becomes a 2/3, the 2/3 becomes a 4/9, and so on: (2/3)s = 2/3 + 4/9 + 8/27 + 16/81 + .... `,
  `This new series is the same as the original, except that the first term is missing. `,
  `Subtracting the new series (2/3)s from the original series s cancels every term in the original but the first, `,
  `s - 2/3s = 1, so s = 3. A similar technique can be used to evaluate any self-similar expression. `,
  `For r =/= 1, the sum of the first n terms of a geometric series is a + ar + ar^2 + ar^3 + ... + ar^(n-1) = SUM(ar^k) from k=0 to k=n-1 = a((1 - r^n)/(1 - r)), where a is the first term of the series, and r is the common ratio. `,
  `We can derive this formula as follows: s = a + ar + ar^2 + ar^3 + ... + ar^(n-1), rs = ar + ar^2 + ar^3 + ar^4 + ... + ar^n, s - rs = a - ar^n, s(1 - r) = a(1 - r^n), so, s = a((1 - r^n)/(1 - r)) (if r =/= 1). `,
  `As n goes to infinity, the absolute value of r must be less than one for the series to converge. `,
  `The sum then becomes a + ar + ar^2 + ar^3 + ar^4 + ... = SUM(ar^k) from k=0 to k=infinity = a/(1 - r), for |r| < 1. `,
  `When a = 1, this can be simplified to 1 + r + r^2 + r^3 + ... = 1/(1 - r), the left-hand side being a geometric series with common ratio r. `,
  `The formula also holds for complex r, with the corresponding restriction, the modulus of r is strictly less than one. `,
  `We can prove that the geometric series converges using the sum formula for a geometric progression: 1 + r + r^2 + r^3 + ... = lim n->infinity 1 + r + r^2 + ... + r^n = lim n->infinity (1 - r^(n + 1))/(1 - r). `,
  `Since (1 + r + r^2 + ... + r^n)(1 − r) = 1 − r^(n+1) and r^(n+1) -> 0 for |r| < 1. `,
  `Convergence of geometric series can also be demonstrated by rewriting the series as an equivalent telescoping series. `,
  `Consider the function, g(K) = (r^K)/(1 - r). Note that 1 = g(0) - g(1), r = g(1) - g(2), r^2 = g(2) - g(3), ... Thus, S = 1 + r + r^2 + r^3 + ... = (g(0) - g(1)) + (g(1) - g(2)) + (g(2) - g(3)) + .... `,
  `If |r| < 1 then g(K) -> 0 as K -> infinity. So S converges to g(0) = 1/(1 - r). `,
  `A repeating decimal can be thought of as a geometric series whose common ratio is a power of 1/10. For example: 0.7777... = 7/10 + 7/100 + 7/1000 + 7/10000 + .... `,
  `The formula for the sum of a geometric series can be used to convert the decimal to a fraction, 0.7777... = a/(1 - r) = (7/10)/(1 - 1/10) = (7/10)/(9/10) = 7/9. `,
  `The formula works not only for a single repeating figure, but also for a repeating group of figures. For example: 0.123412341234... = a/(1 - r) = (1234/10000)/(1 - 1/10000) = (1234/10000)/(9999/10000) = 1234/9999. `,
  `Note that every series of repeating consecutive decimals can be conveniently simplified with the following: 0.09090909... = 09/99 = 1/11. 0.143814381438... = 1439/9999. 0.9999... = 9/9 = 1. `,
  `That is, a repeating decimal with repeat length n is equal to the quotient of the repeating part (as an integer) and 10^n - 1. `,
  `In the study of fractals, geometric series often arise as the perimeter, area, or volume of a self-similar figure. For example, the area inside the Koch snowflake can be described as the union of infinitely many equilateral triangles. `,
  `Each side of the second-level triangle is exactly 1/3 the size of a side of the largest triangle, and therefore has exactly 1/9 the area. Similarly, each third-level triangle has 1/9 the area of a second-level triangle, and so forth. Taking the largest triangle as a unit of area, the total area of the snowflake is 1 + 3(1/9) + 12(1/9)^2 + 48(1/9)^3 + .... `,
  `The first term of this series represents the area of the largest triangle, the second term the total area of the three second-level triangles, the third term the total area of the twelve third-level triangles, and so forth. `,
  `Excluding the initial 1, this series is geometric with constant ratio r = 4/9. The first term of the geometric series is a = 3(1/9) = 1/3, so the sum is 1 + a/(1 - r) = 1 + (1/3)/(1 - 4/9) = 8/5. Thus the Koch snowflake has 8/5 of the area of the base triangle. `,
  `The convergence of a geometric series reveals that a sum involving an infinite number of summands can indeed be finite, and so allows one to resolve many of Zeno's paradoxes. `,
  `For example, Zeno's dichotomy paradox maintains that movement is impossible, as one can divide any finite path into an infinite number of steps wherein each step is taken to be half the remaining distance. `,
  `Zeno's mistake is in the assumption that the sum of an infinite number of finite steps cannot be finite. This is of course not true, as evidenced by the convergence of the geometric series with r = 1/2. `,
  `Book IX, Proposition 35 of Euclid's Elements expresses the partial sum of a geometric series in terms of members of the series. It is equivalent to the modern formula. `,
  `In economics, geometric series are used to represent the present value of an annuity (a sum of money to be paid in regular intervals). `,
  `For example, suppose that a payment of $100 will be made to the owner of the annuity once per year (at the end of the year) in perpetuity. Receiving $100 a year from now is worth less than an immediate $100, because one cannot invest the money until one receives it. In particular, the present value of $100 one year in the future is $100 / (1 + I ), where I is the yearly interest rate. `,
  `Similarly, a payment of $100 two years in the future has a present value of $100 / (1 + I)^2 (squared because two years' worth of interest is lost by not receiving the money right now). Therefore, the present value of receiving $100 per year in perpetuity is SUM($100/(1 + I)^n) for n = 1 to n = infinity which is the infinite series: $100/(1 + I) + $100/(1 + I)^2 + $100/(1 + I)^3 + $100/(1 + I)^4 + .... `,
  `This is a geometric series with common ratio 1 / (1 + I). The sum is the first term divided by (one minus the common ratio): ($100/(1 + I))/(1 - 1/(1 + I)) = $100/I. `,
  `For example, if the yearly interest rate is 10% (I = 0.10), then the entire annuity has a present value of $100 / 0.10 = $1000. `,
  `This sort of calculation is used to compute the APR of a loan (such as a mortgage loan). It can also be used to estimate the present value of expected stock dividends, or the terminal value of a security. `,
];

// DANAIDS //
let danaidsBeginnerGrammar = {
  'verb': ['fill','pour','wash'],
  'origin':['#verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb# #verb#'],
};
let danaidsIntermediateGrammar = {
  'kill': ['kill','murder','assassinate'],
  'husband': ['Lynceus', 'Proteus', 'Busiris', 'Enceladus', 'Lycus', 'Daiphron', 'Istrus', 'Chalcodon', 'Agenor', 'Chaetus', 'Diocorystes', 'Alces', 'Alcmenor', 'Hippothous', 'Euchenor', 'Hippolytus', 'Agaptolemus', 'Cercetes', 'Eurydamas', 'Aegius', 'Argius', 'Archelaus', 'Menemachus', 'Clitus', 'Sthenelus', 'Chrysippus', 'Eurylochus', 'Phantes', 'Peristhenes', 'Hermus', 'Dryas', 'Potamon', 'Cisseus', 'Lixus', 'Imbrus', 'Bromius', 'Polyctor', 'Chthonius', 'Periphas', 'Oeneus', 'Aegyptus', 'Menalces', 'Lampus', 'Idmon', 'Idas', 'Daiphron', 'Pandion', 'Arbelus', 'Hyperbius', 'Hippocorystes',],
  'weddingnight': ['after the wedding', 'the night of the wedding ceremony', 'on my wedding night','on the night of my wedding','on the night of the wedding ceremony'],
  'crime': [
    '#kill# my husband #husband# #weddingnight#',
  ],
  'origin': ['I will not #crime#.'],
};
let danaidsAdvancedStrings = [
  `Bathing is the washing of the body with a liquid, usually water or an aqueous solution, or the immersion of the body in water. It may be practiced for personal hygiene, religious ritual or therapeutic purposes. By analogy, especially as a recreational activity, the term is also applied to sun bathing and sea bathing$1`,
  `Bathing can take place in any situation where there is water, ranging from warm to cold. It can take place in a bathtub or shower, or it can be in a river, lake, water hole, pool or the sea, or any other water receptacle. The term for the act can vary. For example, a ritual religious bath is sometimes referred to as immersion, the use of water for therapeutic purposes can be called a water treatment or hydrotherapy, and two recreational water activities are known as swimming and paddling$1`,
  `Throughout history, societies devised systems to enable water to be brought to population centres$1`,
  `Ancient Indians used elaborate practices for personal hygiene with three daily baths and washing. These are recorded in the works called grihya sutras and are in practice today in some communities$1`,
  `Ancient Greece utilized small bathtubs, wash basins, and foot baths for personal cleanliness. The earliest findings of baths date from the mid-2nd millennium BC in the palace complex at Knossos, Crete, and the luxurious alabaster bathtubs excavated in Akrotiri, Santorini. The Greeks established public baths and showers within gymnasiums for relaxation and personal hygiene. The word gymnasium(γυμνάσιο) comes from the Greek word gymnos(γυμνός), meaning naked$1`,
  `Ancient Rome developed a network of aqueducts to supply water to all large towns and population centres and had indoor plumbing, with pipes that terminated in homes and at public wells and fountains. The Roman public baths were called thermae. The thermae were not simply baths, but important public works that provided facilities for many kinds of physical exercise and ablutions, with cold, warm, and hot baths, rooms for instruction and debate, and usually one Greek and one Latin library. They were provided for the public by a benefactor, usually the Emperor. Other empires of the time didn't show such an affinity for public works, but this Roman practice spread their culture to places where there may have been more resistance to foreign mores. Unusually for the time, the thermae were not class-stratified; being available to all for no charge or a small fee. With the fall of the Roman Empire, the aqueduct system fell into disrepair and disuse. But even before that, during the Christianization of the Empire, changing ideas about public morals led the baths into disfavor$1`,
  `Before the 7th century, the Japanese likely bathed in the many springs in the open, as there is no evidence of closed rooms. In the 6th to 8th centuries (in the Asuka and Nara periods) the Japanese absorbed the religion of Buddhism from China, which had a strong impact on the culture of the entire country. Buddhist temples traditionally included a bathhouse (yuya) for the monks. Due to the principle of purity espoused by Buddhism these baths were eventually opened to the public. Only the wealthy had private baths$1`,
  `The first public bathhouse was mentioned in 1266. In Edo (modern Tokyo), the first sentō was established in 1591. The early steam baths were called iwaburo (岩風呂 "rock pools") or kamaburo (釜風呂 "furnace baths"). These were built into natural caves or stone vaults. In iwaburo along the coast, the rocks were heated by burning wood, then sea water was poured over the rocks, producing steam. The entrances to these "bath houses" were very small, possibly to slow the escape of the heat and steam. There were no windows, so it was very dark inside and the user constantly coughed or cleared their throats in order to signal to new entrants which seats were already occupied. The darkness could be also used to cover sexual contact. Because there was no gender distinction, these baths came into disrepute. They were finally abolished in 1870 on hygienic and moral grounds. Author John Gallagher says bathing "was segregated in the 1870s as a concession to outraged Western tourists"$1`,
  `At the beginning of the Edo period (1603–1868) there were two different types of baths. In Edo, hot-water baths ('湯屋 yuya) were common, while in Osaka, steam baths (蒸風呂 mushiburo) were common. At that time shared bathrooms for men and women were the rule. These bathhouses were very popular, especially for men. "Bathing girls" (湯女 yuna) were employed to scrub the guests' backs and wash their hair, etc. In 1841, the employment of yuna was generally prohibited, as well as mixed bathing. The segregation of the sexes, however, was often ignored by operators of bathhouses, or areas for men and women were separated only by a symbolic line. Today, sento baths have separate rooms for men and women$1`,
  `Spanish chronicles describe the bathing habits of the peoples of Mesoamerica during and after the conquest. Bernal Díaz del Castillo describes Moctezuma (the Mexica, or Aztec, king at the arrival of Cortes) in his Historia verdadera de la conquista de la Nueva España as being "...Very neat and cleanly, bathing every day each afternoon...". Bathing was not restricted to the elite, but was practised by all people; the cronist Tomás López Medel wrote after a journey to Central America that "Bathing and the custom of washing oneself is so quotidian (common) amongst the Indians, both of cold and hot lands, as is eating, and this is done in fountains and rivers and other water to which they have access, without anything other than pure water...$1`,
  `The Mesoamerican bath; known as temazcal in Spanish, from the Nahuatl word temazcalli, a compound of temaz ("steam") and calli ("house"), consists of a room, often in the form of a small dome, with an exterior firebox known as texictle (teʃict͜ɬe) that heats a small portion of the room's wall made of volcanic rocks; after this wall has been heated, water is poured on it to produce steam, an action known as tlasas. As the steam accumulates in the upper part of the room a person in charge uses a bough to direct the steam to the bathers who are lying on the ground, with which he later gives them a massage, then the bathers scrub themselves with a small flat river stone and finally the person in charge introduces buckets with water with soap and grass used to rinse. This bath had also ritual importance, and was vinculated to the goddess Toci; it is also therapeutic when medicinal herbs are used in the water for the tlasas. It is still used in Mexico$1`,
  `Christianity has always placed a strong emphasis on hygiene. Despite the denunciation of the mixed bathing style of Roman pools by early Christian clergy, as well as the pagan custom of women bathing naked in front of men, this did not stop the Church from urging its followers to go to public baths for bathing, which contributed to hygiene and good health according to the Church Father, Clement of Alexandria. The Church also built public bathing facilities that were separate for both sexes near monasteries and pilgrimage sites; also, the popes situated baths within church basilicas and monasteries since the early Middle Ages. Pope Gregory the Great urged his followers on value of bathing as a bodily need$1`,
  `In the Middle Ages, bathing commonly took place in public bathhouses. Public baths were also havens for prostitution, which created some opposition to them. Rich people bathed at home, most likely in their bedroom, as 'bath' rooms were not common. Bathing was done in large, wooden tubs with a linen cloth laid in it to protect the bather from splinters. Additionally, during the Renaissance and Protestant Reformation, the quality and condition of the clothing (as opposed to the actual cleanliness of the body itself) were thought to reflect the soul of an individual. Clean clothing also reflected one's social status; clothes made the man or woman$1`,
  `Furthermore, from the late Middle Ages through to the end of the 18th century, etiquette and medical manuals advised people to only wash the parts of the body that were visible to the public; for example, the ears, hands, feet, and face and neck. This did away with the public baths and left the cleaning of oneself to the privacy of one's home$1`,
  `The switch from woolen to linen clothing by the 16th century also accompanied the decline in bathing. Linen clothing is much easier to clean and maintain – and such clothing was becoming commonplace at the time in Western Europe. Clean linen shirts or blouses allowed people who had not bathed to appear clean and well groomed. The possession of a large quantity of clean linen clothing was a sign of social status. Thus, appearance became more important than personal hygiene. Contemporary medical opinion also supported this claim. Physicians of the period believed that odors, or miasma, such as that which would be found in soiled linens, caused disease. A person could therefore change one's shirt every few days, but avoid baths – which might let the "bad air" into the body through the pores. Consequently, in an age in which there were very few personal bathtubs, laundry was an important and weekly chore which was commonly undertaken by laundresses of the time$1`,
  `Public opinion about bathing began to shift in the middle and late 18th century, when writers argued that frequent bathing might lead to better health. Two English works on the medical uses of water were published in the 18th century that inaugurated the new fashion for therapeutic bathing. One of these was by Sir John Floyer, a physician of Lichfield, who, struck by the remedial use of certain springs by the neighbouring peasantry, investigated the history of cold bathing and published a book on the subject in 1702.  The book ran through six editions within a few years and the translation of this book into German was largely drawn upon by Dr J. S. Hahn of Silesia as the basis for his book called On the Healing Virtues of Cold Water, Inwardly and Outwardly Applied, as Proved by Experience, published in 1738$1`,
  `The other work was a 1797 publication by Dr James Currie of Liverpool on the use of hot and cold water in the treatment of fever and other illness, with a fourth edition published not long before his death in 1805. It was also translated into German by Michaelis (1801) and Hegewisch (1807). It was highly popular and first placed the subject on a scientific basis. Hahn's writings had meanwhile created much enthusiasm among his countrymen, societies having been everywhere formed to promote the medicinal and dietetic use of water; and in 1804 Professor E.F.C. Oertel of Anspach republished them and quickened the popular movement by unqualified commendation of water drinking as a remedy for all diseases.$1`,
  `A popular revival followed the application of hydrotherapy around 1829, by Vincenz Priessnitz, a peasant farmer in Gräfenberg, then part of the Austrian Empire.  This revival was continued by a Bavarian priest, Sebastian Kneipp (1821–1897), "an able and enthusiastic follower" of Priessnitz, "whose work he took up where Priessnitz left it", after he read a treatise on the cold water cure. In Worishofen (south Germany), Kneipp developed the systematic and controlled application of hydrotherapy for the support of medical treatment that was delivered only by doctors at that time. Kneipp's own book My Water Cure was published in 1886 with many subsequent editions, and translated into many languages$1`,
  `Captain R. T. Claridge was responsible for introducing and promoting hydropathy in Britain, first in London in 1842, then with lecture tours in Ireland and Scotland in 1843. His 10-week tour in Ireland included Limerick, Cork, Wexford, Dublin and Belfast, over June, July and August 1843, with two subsequent lectures in Glasgow$1`,
  `Large public baths such as those found in the ancient world and the Ottoman Empire were revived during the 19th century. The first modern public baths were opened in Liverpool in 1829. The first known warm fresh-water public wash house was opened in May 1842$1`,
  `The popularity of wash-houses was spurred by the newspaper interest in Kitty Wilkinson, an Irish immigrant "wife of a labourer" who became known as the Saint of the Slums. In 1832, during a cholera epidemic, Wilkinson took the initiative to offer the use of her house and yard to neighbours to wash their clothes, at a charge of a penny per week, and showed them how to use a chloride of lime (bleach) to get them clean. She was supported by the District Provident Society and William Rathbone. In 1842 Wilkinson was appointed baths superintendent$1`,
  `In Birmingham, around ten private baths were available in the 1830s. Whilst the dimensions of the baths were small, they provided a range of services. A major proprietor of bath houses in Birmingham was a Mr. Monro who had had premises in Lady Well and Snow Hill. Private baths were advertised as having healing qualities and being able to cure people of diabetes, gout and all skin diseases, amongst others. On 19 November 1844, it was decided that the working class members of society should have the opportunity to access baths, in an attempt to address the health problems of the public. On 22 April and 23 April 1845, two lectures were delivered in the town hall urging the provision of public baths in Birmingham and other towns and cities$1`,
  `After a period of campaigning by many committees, the Public Baths and Wash-houses Act received royal assent on 26 August 1846. The Act empowered local authorities across the country to incur expenditure in constructing public swimming baths out of its own funds$1`,
  `The first London public baths was opened at Goulston Square, Whitechapel, in 1847 with the Prince consort laying the foundation stone$1`,
  `Traditional Turkish baths (a variant of the Roman bath) were introduced to Britain by David Urquhart, diplomat and sometime Member of Parliament for Stafford, who for political and personal reasons wished to popularize Turkish culture. In 1850 he wrote The Pillars of Hercules, a book about his travels in 1848 through Spain and Morocco. He described the system of dry hot-air baths used there and in the Ottoman Empire which had changed little since Roman times. In 1856 Richard Barter read Urquhart's book and worked with him to construct a bath. They opened the first modern hot water bath at St Ann's Hydropathic Establishment near Blarney, County Cork, Ireland$1`,
  `The following year, the first public bath of its type to be built in mainland Britain since Roman times was opened in Manchester, and the idea spread rapidly. It reached London in July 1860, when Roger Evans, a member of one of Urquhart's Foreign Affairs Committees, opened a Turkish bath at 5 Bell Street, near Marble Arch. During the following 150 years, over 600 Turkish baths opened in Britain, including those built by municipal authorities as part of swimming pool complexes, taking advantage of the fact that water-heating boilers were already on site$1`,
  `Similar baths opened in other parts of the British Empire. Dr. John Le Gay Brereton opened a Turkish bath in Sydney, Australia in 1859, Canada had one by 1869, and the first in New Zealand was opened in 1874. Urquhart's influence was also felt outside the Empire when in 1861, Dr Charles H Shepard opened the first Turkish baths in the United States at 63 Columbia Street, Brooklyn Heights, New York, most probably on 3 October 1863$1`,
  `By the mid-19th century, the English urbanised middle classes had formed an ideology of cleanliness that ranked alongside typical Victorian concepts, such as Christianity, respectability and social progress. The cleanliness of the individual became associated with his or her moral and social standing within the community and domestic life became increasingly regulated by concerns regarding the presentation of domestic sobriety and cleanliness.$1`,
  `The industry of soapmaking began on a small scale in the 1780s, with the establishment of a soap manufactory at Tipton by James Keir and the marketing of high-quality, transparent soap in 1789 by Andrew Pears of London. It was in the mid-19th century, though, that the large-scale consumption of soap by the middle classes, anxious to prove their social standing, drove forward the mass production and marketing of soap$1`,
  `William Gossage produced low-priced, good-quality soap from the 1850s. William Hesketh Lever and his brother, James, bought a small soap works in Warrington in 1886 and founded what is still one of the largest soap businesses, formerly called Lever Brothers and now called Unilever. These soap businesses were among the first to employ large-scale advertising campaigns$1`,
  `Before the late 19th century, water to individual places of residence was rare. Many countries in Europe developed a water collection and distribution network. London water supply infrastructure developed through major 19th-century treatment works built in response to cholera threats, to modern large-scale reservoirs. By the end of the century, private baths with running hot water were increasingly common in affluent homes in America and Britain$1`,
  `At the beginning of the 20th century, a weekly Saturday night bath had become common custom for most of the population. A half day's work on Saturday for factory workers allowed them some leisure to prepare for the Sunday day of rest. The half day off allowed time for the considerable labor of drawing, carrying, and heating water, filling the bath and then afterward emptying it. To economize, bath water was shared by all family members. Indoor plumbing became more common in the 20th century and commercial advertising campaigns pushing new bath products began to influence public ideas about cleanliness, promoting the idea of a daily shower or bath$1`,
  `One purpose of bathing is for personal hygiene. It is a means of achieving cleanliness by washing away dead skin cells, dirt and soil, and a preventative measure to reduce the incidence and spread of disease. It also reduces body odors$1`,
  `Bathing creates a feeling of well-being and the physical appearance of cleanliness$1`,
  `Bathing may also be practised for religious ritual or therapeutic purposes or as a recreational activity. Bathing may be used to cool or to warm the body of an individual$1`,
  `Therapeutic use of bathing includes hydrotherapy, healing, rehabilitation from injury or addiction, and relaxation$1`,
  `The use of a bath in religious ritual or ceremonial rites include immersion during baptism in Christianity and to achieve a state of ritual cleanliness in a mikvah in Judaism. It is referred to as Ghusl in Arabic to attain ceremonial purity (Taahir) in Islam. All major religions place an emphasis on ceremonial purity, and bathing is one of the primary means of attaining outward purity. In Hindu households, any acts of defilement are countered by undergoing a bath and Hindus also immerse in Sarovar as part of religious rites. In the Sikh religion, there is a place at Golden Temple where the leprosy of Rajni's husband was cured by immersion into the holy sacred pool, and many pilgrims bathe in the sacred pool believing it will cure their illness as well$1`,
  `Where bathing is for personal hygiene, bathing in a bathtub or shower is the most common form of bathing in Western, and many Eastern, countries. Bathrooms usually have a tap, and a shower if it is a modern home, and a huge water heating pot. People take water from the tap or the water-heating pot into a large bucket and use a mug to pour water on themselves. A soap and loofah is used to clean the body after, and then rinsed again using the mug. People most commonly bathe in their home or use a private bath in a public bathhouse. In some societies, bathing can take place in rivers, creeks, lakes or water holes, or any other place where there is an adequate pool of water. The quality of water used for bathing purposes varies considerably. Normally bathing involves use of soap or a soap-like substance, such as shower gel. In southern India people more commonly use aromatic oil and other home-made body scrubs$1`,
  `Bathing occasions can also be occasions of social interactions, such as in public, Turkish, banya, sauna or whirlpool baths$1`,
  `When water is in short supply or a person is not fit to have a standing bath, a wet cloth or sponge can be used, or the person can wash by splashing water over their body. A sponge bath is usually conducted in hospitals, which involves one person washing another with a sponge, while the person being washed remains lying in bed$1`,
  `Ladling water from a container involves using a small container to scoop water out of a large container and pour water over the body, in such a way that this water does not go back into the large container$1`,
  `In Indonesia and Malaysia, this is a traditional method referred to as mandi$1`,
  `In the Indonesian language, mandi is the verb for this process; bak mandi is the large container, and kamar mandi is the place in which this is done. Travel guides often use the word mandi on its own or in various ways such as for the large container and for the process of bathing$1`,
  `The timba (pail) and the tabo (dipper), the two essentials in Philippine bathrooms and bathing areas$1`,
  `In the Philippines, timba (pail) and tabo (dipper) are two essentials in every bathroom$1`,
  `When bathing for cleanliness, normally, people bathe completely naked, so as to make cleaning every part of their body possible. This is the case in private baths, whether in one's home or a private bath in a public bathhouse. In public bathing situations, the social norms of the community are followed, and some people wear a swimsuit or underwear. For example, when a shower is provided in a non-sex segregated area of a public swimming pool, users of the shower commonly wear their swimsuit. The customs can vary depending on the age of a person, and whether the bathing is in a sex segregated situation. In some societies, some communal bathing is also done without clothing$1`,
  `When swimming, not wearing clothing is sometimes called skinny dipping$1`,
  `Babies can be washed in a kitchen sink or a small plastic baby bath, instead of using a standard bath which offers little control of the infant's movements and requires the parent to lean awkwardly or kneel. Bathing infants too often has been linked to the development of asthma or severe eczema according to some researchers, including Michael Welch, chair of the American Academy of Pediatrics' section on allergy and immunology. A safe temperature for the bathwater is generally held to be 32–38 degrees centigrade (90–100 degrees fahrenheit)$1`,
  `Today, most homes in Japan have a bathroom (ofuro), which was often not the case about 30 years ago. Bath water in Japan is much hotter than what is usual in Central Europe. The temperature is usually well above 40°C. In medical literature, 47°C is considered bearable. The heat is considered a prerequisite for complete relaxation. The custom is to thoroughly clean oneself with soap and rinse before entering the tub, so as not to contaminate the bath water. Until the 19th century, the Japanese did not use soap, but rubbed the skin with certain herbs, or rice bran, which was also a natural exfoliant$1`,
  `Sento bathing scene. Japanese woman bathing in a wooden tub (woodcut by Torii Kiyomitsu, late 18th century$1`,
    `In public baths, there is a distinction between those with natural hot springs called, onsen (hot), and the other, the sento. Since Japan is located in a volcanically active region, there are many hot springs, of which about 2000 are swimming pools. Most onsen are in the open countryside, but they are also found in cities. In Tokyo, for example, there are about 25 onsen baths. Locations of known mineral springs spas are on the Western model$1`,
    `An onsen, consists mostly of outdoor pools (rotenburo), which are sometimes at different temperatures. Extremely hot springs, where even experienced or frequent hot-spring bathers can only stay a few minutes, are called jigoku (hell). Many onsen also have saunas, spa treatments and therapy centers. The same rules apply in public baths as in private baths, with bathers required to wash and clean themselves before entering the water. In general, the Japanese bathe naked in bathhouses; bathing suits are not permissible$1`,
    `Bathing scenes were already in the Middle Ages a popular subject of painters. Most of the subjects were women shown nude, but the interest was probably less to the bathing itself rather than to provide the context for representing the nude figure. From the Middle Ages, illustrated books of the time contained such bathing scenes. Biblical and mythological themes which featured bathing were depicted by numerous painters. Especially popular themes included Bathsheba in the bath, in which she is observed by King David, and Susanna in the sight of lecherous old men$1`,
    `In the High Middle Ages, public baths were a popular subject of painting, with rather clear depictions of sexual advances, which probably were not based on actual observations. During the Renaissance and Baroque periods, the gods and nymphs of Greek mythology were depicted bathing in allegorical paintings by artists such as Titian and François Boucher, both of whom painted the goddess Diana bathing. Artists continued to paint Biblical characters bathing, and also sometimes depicted contemporary women bathing in the river, an example being Rembrandt's Woman Bathing$1`,
    `In the 19th century, the use of the bathing scene reached its high point in classicism, realism and impressionism. Oriental themes and harem and turkish baths scenes became popular. These scenes were based on the artists' imagination, because access by men to Islamic women was not generally permitted. In the second half of the century, artists increasingly eschewed the pretexts of mythology and exoticism, and painted contemporary western women bathing. Edgar Degas, for example, painted over 100 paintings with a bathing theme. The subject of Bathers remained popular in avant-garde circles at the outset of the 20th century$1`,
    `Notable artists who have represented bathing scenes: Lawrence Alma-Tadema, Pierre Bonnard, William-Adolphe Bouguereau, François Boucher, Paul Cezanne, Gustave Courbet, Lucas Cranach the Younger, Edgar Degas, Albrecht Durer, Anthony van Dyck, Roger de La Fresnaye, Paul Gauguin, Jean-Leon Gerome, Albert Gleizes, Jean-Auguste-Dominique Ingres, Ernst Ludwig Kirchner, Boris Kustodiev, Max Liebermann, Edouard Manet, Jean Metzinger, Pablo Picasso, Pierre-Auguste Renoir, Sebastiano Ricci, Zinaida Serebriakova, Joaquín Sorolla y Bastida, Domenico Tintoretto, Titian, Anders Zorn$1`,
  ];

  // Camus
  let camusStrings = [
    'The gods had condemned Sisyphus to ceaselessly rolling a rock to the top of a mountain, whence the stone would fall back of its own weight. ',
    'They had thought with some reason that there is no more dreadful punishment than futile and hopeless labor. ',
    'If one believes Homer, Sisyphus was the wisest and most prudent of mortals. ',
    'According to another tradition, however, he was disposed to practice the profession of highwayman. ',
    'I see no contradiction in this. ',
    'Opinions differ as to the reasons why he became the futile laborer of the underworld. ',
    'To begin with, he is accused of a certain levity in regard to the gods. ',
    'He stole their secrets. ',
    'Egina, the daughter of Esopus, was carried off by Jupiter. ',
    'The father was shocked by that disappearance and complained to Sisyphus. ',
    'He, who knew of the abduction, offered to tell about it on condition that Esopus would give water to the citadel of Corinth. ',
    'To the celestial thunderbolts he preferred the benediction of water. ',
    'He was punished for this in the underworld. ',
    'Homer tells us also that Sisyphus had put Death in chains. ',
    'Pluto could not endure the sight of his deserted, silent empire. ',
    'He dispatched the god of war, who liberated Death from the hands of her conqueror. ',
    'It is said that Sisyphus, being near to death, rashly wanted to test his wife\'s love. ',
    'He ordered her to cast his unburied body into the middle of the public square. ',
    'Sisyphus woke up in the underworld. ',
    'And there, annoyed by an obedience so contrary to human love, he obtained from Pluto permission to return to earth in order to chastise his wife. ',
    'But when he had seen again the face of this world, enjoyed water and sun, warm stones and the sea, he no longer wanted to go back to the infernal darkness. ',
    'Recalls, signs of anger, warnings were of no avail. ',
    'Many years more he lived facing the curve of the gulf, the sparkling sea, and the smiles of earth. ',
    'A decree of the gods was necessary. ',
    'Mercury came and seized the impudent man by the collar and, snatching him from his joys, lead him forcibly back to the underworld, where his rock was ready for him. ',
    'You have already grasped that Sisyphus is the absurd hero. ',
    'He is, as much through his passions as through his torture. ',
    'His scorn of the gods, his hatred of death, and his passion for life won him that unspeakable penalty in which the whole being is exerted toward accomplishing nothing. ',
    'This is the price that must be paid for the passions of this earth. ',
    'Nothing is told us about Sisyphus in the underworld. ',
    'Myths are made for the imagination to breathe life into them. ',
    'As for this myth, one sees merely the whole effort of a body straining to raise the huge stone, to roll it, and push it up a slope a hundred times over; one sees the face screwed up, the cheek tight against the stone, the shoulder bracing the clay-covered mass, the foot wedging it, the fresh start with arms outstretched, the wholly human security of two earth-clotted hands. ',
    'At the very end of his long effort measured by skyless space and time without depth, the purpose is achieved. ',
    'Then Sisyphus watches the stone rush down in a few moments toward that lower world whence he will have to push it up again toward the summit. ',
    'He goes back down to the plain. ',
    'It is during that return, that pause, that Sisyphus interests me. ',
    'A face that toils so close to stones is already stone itself! I see that man going back down with a heavy yet measured step toward the torment of which he will never know the end. ',
    'That hour like a breathing-space which returns as surely as his suffering, that is the hour of consciousness. ',
    'At each of those moments when he leaves the heights and gradually sinks toward the lairs of the gods, he is superior to his fate. ',
    'He is stronger than his rock. ',
    'If this myth is tragic, that is because its hero is conscious. ',
    'Where would his torture be, indeed, if at every step the hope of succeeding upheld him? The workman of today works everyday in his life at the same tasks, and his fate is no less absurd. ',
    'But it is tragic only at the rare moments when it becomes conscious. ',
    'Sisyphus, proletarian of the gods, powerless and rebellious, knows the whole extent of his wretched condition: it is what he thinks of during his descent. ',
    'The lucidity that was to constitute his torture at the same time crowns his victory. ',
    'There is no fate that can not be surmounted by scorn. ',
    'If the descent is thus sometimes performed in sorrow, it can also take place in joy. ',
    'This word is not too much. ',
    'Again I fancy Sisyphus returning toward his rock, and the sorrow was in the beginning. ',
    'When the images of earth cling too tightly to memory, when the call of happiness becomes too insistent, it happens that melancholy arises in man\'s heart: this is the rock\'s victory, this is the rock itself. ',
    'The boundless grief is too heavy to bear. ',
    'These are our nights of Gethsemane. ',
    'But crushing truths perish from being acknowledged. ',
    'Thus, Edipus at the outset obeys fate without knowing it. ',
    'But from the moment he knows, his tragedy begins. ',
    'Yet at the same moment, blind and desperate, he realizes that the only bond linking him to the world is the cool hand of a girl. ',
    'Then a tremendous remark rings out: "Despite so many ordeals, my advanced age and the nobility of my soul make me conclude that all is well." Sophocles\' Edipus, like Dostoevsky\'s Kirilov, thus gives the recipe for the absurd victory. ',
    'Ancient wisdom confirms modern heroism. ',
    'One does not discover the absurd without being tempted to write a manual of happiness. ',
    '"What!---by such narrow ways--?" There is but one world, however. ',
    'Happiness and the absurd are two sons of the same earth. ',
    'They are inseparable. ',
    'It would be a mistake to say that happiness necessarily springs from the absurd. ',
    'discovery. ',
    'It happens as well that the felling of the absurd springs from happiness. ',
    '"I conclude that all is well," says Edipus, and that remark is sacred. ',
    'It echoes in the wild and limited universe of man. ',
    'It teaches that all is not, has not been, exhausted. ',
    'It drives out of this world a god who had come into it with dissatisfaction and a preference for futile suffering. ',
    'It makes of fate a human matter, which must be settled among men. ',
    'All Sisyphus\' silent joy is contained therein. ',
    'His fate belongs to him. ',
    'His rock is a thing Likewise, the absurd man, when he contemplates his torment, silences all the idols. ',
    'In the universe suddenly restored to its silence, the myriad wondering little voices of the earth rise up. ',
    'Unconscious, secret calls, invitations from all the faces, they are the necessary reverse and price of victory. ',
    'There is no sun without shadow, and it is essential to know the night. ',
    'The absurd man says yes and his efforts will henceforth be unceasing. ',
    'If there is a personal fate, there is no higher destiny, or at least there is, but one which he concludes is inevitable and despicable. ',
    'For the rest, he knows himself to be the master of his days. ',
    'At that subtle moment when man glances backward over his life, Sisyphus returning toward his rock, in that slight pivoting he contemplates that series of unrelated actions which become his fate, created by him, combined under his memory\'s eye and soon sealed by his death. ',
    'Thus, convinced of the wholly human origin of all that is human, a blind man eager to see who knows that the night has no end, he is still on the go. ',
    'The rock is still rolling. ',
    'I leave Sisyphus at the foot of the mountain! One always finds one\'s burden again. ',
    'But Sisyphus teaches the higher fidelity that negates the gods and raises rocks. ',
    'He too concludes that all is well. ',
    'This universe henceforth without a master seems to him neither sterile nor futile. ',
    'Each atom of that stone, each mineral flake of that night filled mountain, in itself forms a world. ',
    'The verb itself toward the heights is enough to fill a man\'s heart. ',
    'One must imagine Sisyphus happy. '
  ];
